export const WeaponAbilities = [
  "Anti-Beast (+1 Rend)",
  "Anti-Cavalry (+1 Rend)",
  "Anti-Charge (+1 Rend)",
  "Anti-Flyer (+1 Rend)",
  "Anti-Hero (+1 Rend)",
  "Anti-Infantry (+1 Rend)",
  "Anti-Manifestation (+1 Rend)",
  "Anti-Monster (+1 Rend)",
  "Anti-Priest (+1 Rend)",
  "Anti-Terrain (+1 Rend)",
  "Anti-Warmachine (+1 Rend)",
  "Anti-Wizard (1+ Rend)",
  "Charge (+1 Damage)",
  "Companion",
  "Crit (2 Hits)",
  "Crit (Auto-wound",
  "Crit (Mortal)",
  "Shoot in Combat",
];
