// export enum FactionWeaponsBanners {
//   BladesOfKhorne = "1",
//   CitiesOfSigmar = "2",
//   DaughtersOfKhaine = "3",
//   DisciplesOfTzeench = "4",
//   FleshEaterCourts = "5",
//   Fyreslayers = "6",
//   GloomspiteGitz = "7",
//   HedonitesOfSlaanesh = "8",
//   IdonethDeepkin = "9",
//   KharadronOverlords = "11",
//   LuminethRealmLords = "22",
//   MaggotkinOfNurgle = "33",
//   Nighthaunt = "44",
//   OgorMawtribes = "55",
//   OrrukIronjawz = "66",
//   OrrukKruleBoyz = "77",
//   OssiarchBonereapers = "88",
//   Seraphon = "src/assets/FactionBackgrounds/Order/Seraphon/Serapon_Weapon_Banner.png",
//   Skaven = "99",
//   SlavesToDarkness = "111",
//   SonsOfBehemat = "222",
//   SoulblightGravelords = "333",
//   StormcastEternals = "33333",
//   Sylvaneth = "444",
// }
//
