export enum FactionTemplates {
  BladesOfKhorne = "src/assets/FactionBackgrounds/Chaos/Khorne/Khorne_Warscroll_Template.png",
  CitiesOfSigmar = "2",
  DaughtersOfKhaine = "3",
  DisciplesOfTzeench = "4",
  FleshEaterCourts = "5",
  Fyreslayers = "6",
  GloomspiteGitz = "7",
  HedonitesOfSlaanesh = "src/assets/FactionBackgrounds/Chaos/Slaanesh/Slaanesh_Warscroll_Template.png",
  IdonethDeepkin = "9",
  KharadronOverlords = "11",
  LuminethRealmLords = "22",
  MaggotkinOfNurgle = "33",
  Nighthaunt = "44",
  OgorMawtribes = "55",
  OrrukIronjawz = "66",
  OrrukKruleBoyz = "77",
  OssiarchBonereapers = "88",
  Seraphon = "src/assets/FactionBackgrounds/Order/Seraphon/Seraphon_Warscroll_Template.png",
  Skaven = "99",
  SlavesToDarkness = "111",
  SonsOfBehemat = "222",
  SoulblightGravelords = "333",
  StormcastEternals = "src/assets/FactionBackgrounds/Order/Stormcast/Stormcast_Warscroll_Template.png",
  Sylvaneth = "444",
}

export enum FactionBanners {
  BladesOfKhorne = "src/assets/FactionBackgrounds/Chaos/Khorne/Khorne_Weapon_Banner.png",
  CitiesOfSigmar = "2",
  DaughtersOfKhaine = "3",
  DisciplesOfTzeench = "4",
  FleshEaterCourts = "5",
  Fyreslayers = "6",
  GloomspiteGitz = "7",
  HedonitesOfSlaanesh = "src/assets/FactionBackgrounds/Chaos/Slaanesh/Slaanesh_Weapon_Banner.png",
  IdonethDeepkin = "9",
  KharadronOverlords = "11",
  LuminethRealmLords = "22",
  MaggotkinOfNurgle = "33",
  Nighthaunt = "44",
  OgorMawtribes = "55",
  OrrukIronjawz = "66",
  OrrukKruleBoyz = "77",
  OssiarchBonereapers = "88",
  Seraphon = "src/assets/FactionBackgrounds/Order/Seraphon/Seraphon_Weapon_Banner.png",
  Skaven = "99",
  SlavesToDarkness = "111",
  SonsOfBehemat = "222",
  SoulblightGravelords = "333",
  StormcastEternals = "src/assets/FactionBackgrounds/Order/Stormcast/Stormcast_Weapon_Banner.png",
  Sylvaneth = "444",
}
